name: Checks
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    name: Installation test on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    if: "!contains(github.event.head_commit.message, '[SKIP-CI]')"
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          install:
            - 'install.sh'
    - name: 'Install Google drive upload'
      if: steps.filter.outputs.install == 'true'
      run: |
          set -e
          sh install.sh
              PATH="${HOME}/.google-drive-upload/bin:${PATH}"
              gupload --info && gsync --help
          sh install.sh -U && sh install.sh --posix -B master
              gupload --info && gsync --help
          sh install.sh -U  && sh install.sh -c custom_gupload sync="custom_gsync"
              custom_gupload --info && custom_gsync --help
    - name: 'Format and merge test'
      run: |
          set -e
          { { command -v apt-get && apt-get install snapd -yqq && snap install shfmt ;} ||
            { command -v brew && brew install shfmt ;} ;} 2>| /dev/null 1>&2
          sh merge.sh
          { [ -n "$(git diff)" ] && printf "%s\n" "Error: Format scripts and run merge.sh before pushing the commits." && git diff && exit 1 ;} || :
